first commit
kotovski000/go-rest-api-homework pull request #1
Opened 2024-03-11 21:34 UTC by kotovski000

2024-03-11 23:08 UTC, dirtymew requested changes
Привет Дмитрий

хорошая работа - API энпоинты описал верно, убрал все main.go

Зачет пока не могу поставить - есть что испрвить - см комметарии к PR

2024-03-11 23:08 UTC, dirtymew commented on main.go
> +	delete(tasks, taskID)
сначала нужно проверить есть ли ключ в мапе - если нет то вернуть ошибку

см задание
```
В случае ошибки или отсутствия задачи в мапе сервер должен вернуть статус 400 Bad Request.
Во всех обработчиках тип контента Content-Type — application/json.
```

2024-03-11 23:08 UTC, dirtymew commented on main.go
> +func getTaskByIDHandler(w http.ResponseWriter, r *http.Request) {
тут  стоит упростить название функции `getTaskByID` достаточно

2024-03-11 23:08 UTC, dirtymew commented on main.go
> +	w.WriteHeader(http.StatusCreated)
проверь какой  Content-Type  возвращается?

2024-03-11 23:08 UTC, dirtymew commented on main.go
> +	tasks[newTask.ID] = newTask
тут по хорошему нужна валидация полученных данных
и нужно определиться что делат энпоинт - создает, создает и обновляет или обновляет.
судя по тому что код ответа 201 - то энпоинт должен только создавать новый обьект - сейчас это не так, можно обновить уже существуюший

2024-03-11 23:08 UTC, dirtymew commented on main.go
> +	_, err := buf.ReadFrom(r.Body)
тут нет ошибки - на будущее посмотри еще [Decoder](https://pkg.go.dev/encoding/json#NewDecoder)

2024-03-12 10:40 UTC, dirtymew approved these changes
Дмитрий 

вопросов больше нет - зачет

2024-03-12 10:40 UTC, dirtymew commented on main.go
> +	tasksJSON, err := json.Marshal(tasks)
тут обрати внимание что возвращается обьект а не массив обьектов - это не очень правильно. но раз такой пример был в теории - возвращать на переделку не буду

2024-03-12 11:52 UTC, kotovski000 commented on main.go
> +	tasksJSON, err := json.Marshal(tasks)
Понял. Спасибо. Если Вас не затруднит, не могли бы Вы привести пример кода, который должен работать правильно, т.е. чтобы возвращался массив объектов

2024-03-12 12:01 UTC, dirtymew commented on main.go
> +	tasksJSON, err := json.Marshal(tasks)
@kotovski000 для данного пример можно просто переложить из мапы в массив.
```
taskList := []task
for _, task := tasks {
   tasklist := append(tasklist, task)
}
```
еще потом можно отсортировать по id
```
sort.Slice(taskList, func(i, j int) bool {
  return taskList[i].ID < taskList[j].ID
})
```

2025-01-07 21:43 UTC, merged